#!/bin/sh
if [ "$1" = "ls" ]; then
	gitdblist
	return 0
fi

if [ -f "$GITDB_HOME/custom_jre/bin/java" ]; then
    echo "Running from CUSTOM JRE"
    "$GITDB_HOME/custom_jre/bin/java" -Dlogging.level.root=WARN -jar "$GITDB_HOME"/gitdb-0.0.2-SNAPSHOT.jar "$@"
else
    java -Dlogging.level.root=WARN -jar "$GITDB_HOME"/gitdb-0.0.2-SNAPSHOT.jar "$@"
fi

if [ $? -eq 0 ]; then
    if [ "$1" = "cd" ]; then
      cat $GITDB_HOME/run_cd
      . $GITDB_HOME/run_cd
      echo ""
    fi
else
    echo FAIL
fi